---
title: "SARIMA+Fourier"
output: html_document
---

# Set up! 
```{r}
libraries <- c('forecast','here','tidyverse','zoo','Kendall','tseries','outliers','smooth', "openxlsx", "readxl", "stats")
lapply(libraries,require,character.only=T)
here()

demand <- read.csv(here("Data",'Processed','CleanDemand_v1.csv'))
demand <- select(.data = demand, !X)
demand <- mutate(.data=demand, date = ymd(date))

summary(demand)
```
# Convert to Time Series
```{r}
demand_msts <- msts(data = demand[,2], start = c(2005,01,01), seasonal.periods = c(7,365.25))
demand_msts <- na.interp(demand_msts,linear = T)
autoplot(demand_msts)
Acf(demand_msts, lag.max = 48)
Pacf(demand_msts, lag.max = 48)
```

# view the decomposition for sanity
```{r}
demand_msts %>% mstl() %>%
  autoplot()
```

# Training & Testing

```{r}
# training data
TrainingWindow = 365
demand_msts_training <- subset(demand_msts,
                                   end = length(demand_msts)-TrainingWindow)

#create a subset for testing purpose
demand_msts_testing <- subset(demand_msts,
                            start = length(demand_msts)-TrainingWindow+1,
                            end = length(demand_msts)-TrainingWindow+30)


autoplot(demand_msts_training)
autoplot(demand_msts_testing)
```



# using auto.arima




