---
title: "Salzberg_DataCleanAttempt1"
author: "Josh Salzberg"
date: "2026-03-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup
```{r}
libraries <- c('forecast','here','tidyverse','zoo','Kendall','tseries','outliers','smooth', "openxlsx", "readxl", "stats")
lapply(libraries,require,character.only=T)
here()
```

## Import Data
```{r}
demand_init <- read_excel(
  path=here('Data', "Raw","load.xlsx"),
  col_names=T) 

humid_init <- read_excel(
  path=here('Data', "Raw","relative_humidity.xlsx"),
  col_names=T) 

temp_init <- read_excel(
  path=here('Data', "Raw","temperature.xlsx"),
  col_names=T) 

summary(demand_init)
summary(humid_init)
summary(temp_init)
```


## Clean Data
```{r}
demand_clean <- demand_init %>% 
  mutate(date = ymd(date)) %>% 
  pivot_longer(cols = c(3:26), names_to = "hour", values_to = "load") %>% 
  group_by(date) %>% 
    summarize(avg_load=mean(load))
write.csv(demand_clean, file = here("Data","Processed","Salzberg_CleanDemand.csv"))


humid_clean <- humid_init %>% 
  mutate(date = ymd(date)) %>% 
  pivot_longer(cols = c(3:30), names_to = "RH_source",  values_to = "humidity") %>% 
  group_by(date) %>% 
    summarize(avg_humidity=mean(humidity))
write.csv(humid_clean, file = here("Data","Processed","Salzberg_CleanHumidity.csv"))


temp_clean <- temp_init %>% 
  mutate(date = ymd(date)) %>% 
  pivot_longer(cols = c(3:30), names_to = "T_source", values_to = "temp") %>% 
  group_by(date) %>% 
    summarize(avg_temp=mean(temp))
write.csv(temp_clean, file = here("Data","Processed", "Salzberg_CleanTemp.csv"))

```


# Visualize Series

```{r}
ggplot(data = demand_clean, aes(x = date, y = avg_load))+
  geom_line()+
  labs(title = "Average Daily Electricity Demand",
       y = "Average Electricity Demand per Day")

ggplot(data = humid_clean, aes(x = date, y = avg_humidity))+
  geom_line()+
  labs(title = "Average Daily Humidity",
       y = "Average Humidity per Day")

ggplot(data = temp_clean, aes(x = date, y = avg_temp))+
  geom_line()+
  labs(title = "Average Daily Temperature",
       y = "Average Temperature per Day")
```


