---
title: "Salzberg_SimpleSeasNaive1"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Set up & Load Data
```{r}
libraries <- c('forecast','here','tidyverse','zoo','Kendall',
               'tseries','outliers','smooth', "openxlsx", "readxl",
               "stats",'prophet')
lapply(libraries,require,character.only=T)
here()

demand <- read.csv(here("Data",'Processed','CleanDemand_v1.csv'))
demand <- select(.data = demand, !X)
demand <- mutate(.data=demand, date = ymd(date))

summary(demand)

```

# Convert to Time Series
```{r}
demand_ts <- msts(data = demand[,2], start = c(2005,1), seasonal.periods = c(7,365.25))
demand_ts <- na.interp(demand_ts,linear = T)
demand_ts <- msts(data = demand[,2], start = c(2005,1), seasonal.periods = c(7,365.25))
autoplot(demand_ts)
Acf(demand_ts, lag.max = 48)
Pacf(demand_ts, lag.max = 48)
```


# Decompose demand_ts
```{r}
decomp_demand_ts <- decompose(demand_ts, type = "additive")

autoplot(decomp_demand_ts)
```


# Divide into Training and Testing Data
```{r}
# training data
TrainingWindow = 365
demand_ts_training <- subset(demand_ts,
                                   end = length(demand_ts)-TrainingWindow)
demand_ts_training <- msts(demand_ts_training, seasonal.periods = c(7,365.25))

#create a subset for testing purpose
demand_ts_testing <- subset(demand_ts,
                            start = length(demand_ts)-TrainingWindow+1,
                            end = length(demand_ts)-TrainingWindow+31)
demand_ts_testing <- msts(demand_ts_testing, seasonal.periods = c(7,365.25))

autoplot(demand_ts_training)
autoplot(demand_ts_testing)
```

# Simple Seasonal Naive run & review
```{r}
observed <- demand[(nrow(demand)-TrainingWindow+1):(nrow(demand)-TrainingWindow+31),"avg_load"]
SNAIVE_fore <- snaive(y=demand_ts_training, h=31)
checkresiduals(SNAIVE_fore)

SNAIVE_accuracy <- accuracy(SNAIVE_fore$mean, observed)
plot(SNAIVE_accuracy)
plot(SNAIVE_fore)
```


# July 2011 Forecast:
```{r}
SNAIVE_fore_final <- snaive(demand_ts, h = 31)
checkresiduals(SNAIVE_fore_final)
julyforecast <- data.frame(SNAIVE_fore_final$mean)

```



# AUTO.ARIMA VS AUTO.SARIMA
```{r}
auto_arima_test <- auto.arima(y=demand_ts_training,
                              max.p = 2,
                              max.d = 2,
                              max.q = 2, 
                              max.P = 0,
                              max.D = 0,
                              max.Q = 0, seasonal = F)
print(auto_arima_test)
auto_arima_forecast <- forecast(auto_arima_test, h = 31)
autoplot(auto_arima_forecast)


# auto_sarima_test <- auto.arima(y=demand_ts_training,
#                               max.p = 3,
#                               max.d = 1,
#                               max.q = 3, 
#                               max.P = 3,
#                               max.D = 1,
#                               max.Q = 3,
#                               seasonal = T)
# print(auto_sarima_test)
# auto_sarima_forecast <- forecast(auto_sarima_test, h = 31)
# autoplot(auto_sarima_forecast)
# df_compare_auto_AICs <- data.frame(AIC(auto_arima_test), AIC(auto_sarima_test))


# ARIMA + FOURIER 
auto_arima_fourier_fit <- auto.arima(demand_ts_training, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(demand_ts_training, 
                                          K=c(2,24))
                             )
summary(auto_arima_fourier_fit)
checkresiduals(auto_arima_fourier_fit)
#Forecast with ARIMA fit
auto_arima_fourier_forecast <- forecast(auto_arima_fourier_fit,
                           xreg=fourier(demand_ts_training,
                                        K=c(2,24),
                                        h=31),
                           h=31)


# STL+ETS
ets_train <-  stlf(demand_ts_training,h=31, s.window = "periodic")

#Neural 
neural_train <- nnetar(demand_ts_training,
                 p=2,
                 P=0,
                 xreg=fourier(demand_ts_training,
                                        K=c(3,4)))
neural_fore <- forecast(neural_train, 
                   h=31,
                   xreg=fourier(demand_ts_training, 
                                          K=c(3,4),h=31))

# PROPHET
colnames(demand) <-  c("ds",'y')
df <- prophet(demand)
future <- make_future_dataframe(df,periods = 31)
tail(future)
forecast <- predict(df,future)
tail(forecast)
plot(df,forecast)
prophet_plot_components(df,forecast)


df_compare_accuracy <- as.data.frame(rbind(accuracy(SNAIVE_fore$mean, observed), 
         accuracy(auto_arima_forecast$mean,observed),
         accuracy(auto_arima_fourier_forecast$mean,observed), 
         accuracy(ets_train$mean,observed), 
         accuracy(neural_fore$mean,observed), 
         accuracy(forecast$yhat,observed)))
row.names(df_compare_accuracy) <- c('snaive','auto arima',
                                    'auto arima+fourier',
                                    'ets','neural','prophet')
```

```{r}
final_fourier <- auto.arima(demand_ts, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(demand_ts, 
                                          K=c(2,24)))
final_fourier_forecast <- forecast(final_fourier,
                           xreg=fourier(demand_ts,
                                        K=c(2,24),
                                        h=31),
                           h=31)


autoplot(final_fourier_forecast) +
  ylab("Average Daily Load (kWh)") +
  xlab("Year") +
  ggtitle("Seasonal Naive: July 2011 Forecast") +
  theme_classic()
```

## Export forecast for Kaggle

```{r}
july2011_dates <- seq(as.Date("2011-07-01"), as.Date("2011-07-31"), by = "day")

submission <- data.frame(
  date = july2011_dates,
  load = as.numeric(final_fourier_forecast$mean)
)

write.csv(submission,
          file = "Submissions/gilman_salzberg_arima_fourier.csv",
          row.names = FALSE)

head(submission)
```